config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events, only: [:index,:new,:create ]
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    respond_to do |format|
      format.html
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path }
      else
        format.html { render 'index'}
      end
    end
  end

  def event_params
    params.require(:event).permit(:name,:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_new.html.erb
<div id="button"> X </div>
<%= form_for @event do |e| %>
  <%= e.label :name, class: 'test' %>
  <%= e.text_field :name %><br>

  <%= e.label :description %>
  <%= e.text_field :description %><br>

  <%= e.submit %>
  <%end%>

app/views/events/index.html.erb
<div id="count"> </div>
<%=link_to("new", new_event_path,remote: true) %>
<div id="events">
  <% @events.each do |e| %>
    Name: <%= e.name %> <br>
    Desc: <%= e.description %> <br>
  <%end%>
</div>

<div id="event_new">

</div>

<!-- <%= react_component 'Events', { data: @events } %> -->

app/views/events/new.js.erb
// tutaj wszystkie funkcje dotyczące new
$(document).ready(function(){
    if($('#event_new').is(':visible')){
      $('#event_new').html("<%= j render partial: 'new.html.erb'%>");
    }else{
      $('#event_new').show();
    }
    $('#button').click(function() {
      $('#event_new').hide();
    });
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebCalendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>